remake with symbols infrastructure
SciML/SciMLBase.jl pull request #262
Opened 2022-09-23 16:12 UTC by xtalax

Infrastructure for remaking with symbols where appropriate

2022-09-24 09:55 UTC, ChrisRackauckas commented
This isn't split appropriately and will heavily invalidate. Instead, make this drop the arg `prob.f.sys` appropriately (checking for existence etc.) in a subfunction, and extend that on a dispatch for `AbstractSystem`

2022-09-24 13:12 UTC, ChrisRackauckas commented on src/remake.jl
> +            p = handle_varmap(p, prob.f.sys)
you're missing the basic dispatch here

2022-09-26 04:55 UTC, YingboMa commented on src/remake.jl
> +        if hasproperty(prob.f, :sys) && hasproperty(prob.f.sys, :ps)
We should handle `u0` as well.

2022-09-26 18:30 UTC, ChrisRackauckas approved these changes

2022-09-26 18:30 UTC, ChrisRackauckas commented
Format

2022-09-27 02:41 UTC, YingboMa requested changes
`prob.f.sys.xxx` is wrong. getproperty of a system only means to get the variable in the system. You should call `getfield` directly.

2022-09-27 02:42 UTC, YingboMa commented on src/remake.jl
> +                u0 = handle_varmap(u0, prob.f.sys, field = :states, defaults = prob.f.sys.defaults)
Shouldn't the default be constructed from the current states and parameters that the problem holds?

2022-09-27 02:44 UTC, YingboMa commented on src/remake.jl
> +                p = handle_varmap(p, prob.f.sys, field = :ps, defaults = prob.f.sys.ps .=> prob.p)
This parameters could depend on the initial condition, so you should include `prob.u0` map as well.

2022-09-28 13:25 UTC, ChrisRackauckas commented on src/remake.jl
> +                                   defaults = getfield(prob.f.sys, :states) .=> prob.u0)
this should also have p

2022-10-10 18:03 UTC, merged